plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.KoreaItAcademy.OurNotion'
version = '0.0.1'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-web-services'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	// Spring Boot WebSocket
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	// Spring Security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	// Spring Boot JSON 처리 (JSON 데이터 주고받기)
	implementation 'org.springframework.boot:spring-boot-starter-json'
	// Spring Boot to Node.js Connection use by Http protocol (Using WebClient)
	implementation 'org.springframework.boot:spring-boot-starter-webflux'  // include WebClient
	//Oracle 19c dependency
	implementation group: 'com.oracle.database.jdbc', name: 'ojdbc8', version: '23.6.0.24.10'
	implementation group: 'com.oracle.database.nls', name: 'orai18n', version: '23.6.0.24.10'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
