spring.application.name=OurNotion
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:FREE
spring.datasource.username=SYSTEM
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA ?? (??)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

# ??? ? ?? (HikariCP)
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariPool-1
spring.datasource.hikari.max-lifetime=1800000

# X-Frame-Options ?? ??
# ?? ???? iframe? ??? ? ??? ??
spring.security.headers.frame-options= SAMEORIGIN
